// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  serSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ser',
    },
  ],

  aplicacionesWebSidebar: [
    {
      type: 'autogenerated',
      dirName: 'aplicaciones_web',
    },
  ],

  programacionSidebar: [
    {
      type: 'autogenerated',
      dirName: 'introduccion_programacion',
    },
  ],

  proyectoSidebar: [
    {
      type: 'autogenerated',
      dirName: 'proyectoIntermodular',
    },
  ],
};

export default sidebars;


